[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.17.0"

[[override]]
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"
  name = "github.com/ugorji/go"

[[constraint]]
  version = "v0.11.11"
  name = "github.com/hashicorp/terraform"

  [constraint.metadata]
    govendor-override = true
    govendor-exclude-prefixes = [
      "github.com/golang/protobuf",
      "github.com/mattn/go-isatty",
      "github.com/ugorji/go",
      "google.golang.org/grpc",
    ]
