name: CI & Downstream Testing
on: [pull_request]

jobs:
  build:
    name: Build and Test Bridge
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out source code
        uses: actions/checkout@master
      - name: Download module dependencies
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go mod download
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -v ./...

  downstream-aws:
    needs: build
    name: Test AWS Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.9
      - name: Install Pulumi CLI
        uses: jen20/action-install-pulumi-cli@releases/v1
      - name: Install tf2pulumi
        uses: jen20/action-install-tf2pulumi@releases/v1
        with:
          tf2pulumi-version: 0.6.0

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: jen20/action-test-provider-downstream@releases/v1
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          downstream-name: pulumi-aws
          downstream-url: https://github.com/pulumi/pulumi-aws

  downstream-azure:
    needs: build
    name: Test Azure Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.9
      - name: Install Pulumi CLI
        uses: jen20/action-install-pulumi-cli@releases/v1
      - name: Install tf2pulumi
        uses: jen20/action-install-tf2pulumi@releases/v1
        with:
          tf2pulumi-version: 0.6.0

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: jen20/action-test-provider-downstream@releases/v1
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          downstream-name: pulumi-azure
          downstream-url: https://github.com/pulumi/pulumi-azure

  downstream-gcp:
    needs: build
    name: Test GCP Downstream
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.9
      - name: Install Pulumi CLI
        uses: jen20/action-install-pulumi-cli@releases/v1
      - name: Install tf2pulumi
        uses: jen20/action-install-tf2pulumi@releases/v1
        with:
          tf2pulumi-version: 0.6.0

      - name: Check out source code
        uses: actions/checkout@master
      - name: Test Downstream
        uses: jen20/action-test-provider-downstream@releases/v1
        env:
          GOPROXY: "https://proxy.golang.org"
        with:
          downstream-name: pulumi-gcp
          downstream-url: https://github.com/pulumi/pulumi-gcp
